const STATE_KEY='ord_door_ops_v3',OLD_KEY='ord_door_ops_v2',EMP_KEY='ord_customer_care_fall_2026_v3',DAY=864e5;
let state={days:{}},employees=[],pendingFile=null,calendarDate=new Date(),selectedDate=iso(new Date()),flightTab='all';
const $=id=>document.getElementById(id),norm=v=>String(v??'').trim().toLowerCase(),uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function iso(d){d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function pretty(s){return new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function empName(e){return `${e.lastName||''}${e.firstName?`, ${e.firstName}`:''}`.replace(/^, /,'')||e.name||'Unnamed employee'}
function timeSeconds(v){const s=String(v??'').trim();if(!s)return null;if(/^\d+:\d{1,2}$/.test(s)){const[m,x]=s.split(':').map(Number);return m*60+x}const n=Number(s);return Number.isFinite(n)?Math.round(n*60):null}
function bodyType(equip){const c=String(equip||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(/777|787|789/.test(c))return{type:'WB',target:210,text:'03:30'};if(/319|320|321|738/.test(c))return{type:'NB',target:150,text:'02:30'};return{type:'Unknown',target:null,text:'N/A'}}
function calculate(f){const a=bodyType(f.equip),s=timeSeconds(f.opening);return{...f,aircraftType:a.type,target:a.text,openingSeconds:s,metricMet:a.target===null||s===null?null:s<=a.target,lateOpening:a.target!==null&&s!==null&&s>a.target}}
const docs=()=>({agentId:'',agentName:'',csm:'',shift:'',reason:'',action:'',followUp:'',positioning:''});
async function boot(){try{employees=JSON.parse(localStorage.getItem(EMP_KEY)||'null')||await fetch('data/employees.json').then(r=>r.json())}catch{employees=[]}try{state={days:{},...JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}}catch{}if(!Object.keys(state.days).length)migrate();cleanup();bind();renderAll()}
function migrate(){try{const old=JSON.parse(localStorage.getItem(OLD_KEY)||'{}');if(!old.days)return;state.days=old.days;Object.values(state.days).forEach(d=>d.flights=(d.flights||[]).map(f=>{const r=(old.records||[]).find(x=>x.flightId===f.id)||{};return calculate({...docs(),...f,...r,flightNumber:f.flightNumber||r.flight||'',opening:f.opening||r.duration||''})}))}catch{}}
function cleanup(){const cut=Date.now()-7*DAY;Object.keys(state.days).forEach(d=>{if(new Date(`${d}T23:59:59`).getTime()<cut)delete state.days[d]});saveState()}
function saveState(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}function saveEmployees(){localStorage.setItem(EMP_KEY,JSON.stringify(employees))}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c)hide(c.dataset.close)});$('reportFile').onchange=e=>{pendingFile=e.target.files[0];if(pendingFile){$('reportDate').value=iso(new Date());show('uploadModal')}};$('uploadForm').onsubmit=importReport;$('recordForm').onsubmit=saveFlight;$('agentSearch').oninput=searchAgents;$('recordEquip').oninput=preview;$('recordDuration').oninput=preview;$('employeeForm').onsubmit=saveEmployee;$('deleteEmployeeBtn').onclick=deleteEmployee;$('exportBtn').onclick=exportData;window.onclick=e=>{if(e.target.classList.contains('modal'))hide(e.target.id)}}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='calendar')renderCalendar();if(v==='flightWorkspace')renderFlights();if(v==='employees')renderEmployees()}
function show(id){$(id).classList.add('show')}function hide(id){$(id).classList.remove('show');if(id==='uploadModal'){$('reportFile').value='';pendingFile=null}}function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2500)}
function readSheet(file){return new Promise((ok,bad)=>{if(file.name.toLowerCase().endsWith('.csv'))Papa.parse(file,{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim(),complete:r=>ok(r.data),error:bad});else{const fr=new FileReader();fr.onload=()=>{try{const wb=XLSX.read(fr.result,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];ok(XLSX.utils.sheet_to_json(ws,{defval:'',raw:false}))}catch(e){bad(e)}};fr.onerror=()=>bad(fr.error);fr.readAsArrayBuffer(file)}})}
function pick(r,...names){for(const n of names){const k=Object.keys(r).find(x=>norm(x)===norm(n));if(k&&String(r[k]??'').trim())return String(r[k]).trim()}return''}
function normalizeFlight(r,i,date){const flight=pick(r,'Arr. Flt.','Arr Flt.','Arrival Flight','Dep. Flt.','Dep Flt.','Flight Number'),opening=pick(r,'Door Opening (Mins.)','Door Opening','Door Open (Mins.)');if(!flight||!opening)return null;return calculate({id:`${date}-${i}-${uid()}`,date,flightNumber:flight,gate:pick(r,'ETA/Actual Gate','Sch Arr. Gate','Sch Arr Gate','ETD/Actual Gate','Sch Dep. Gate','Sch Dep Gate'),equip:pick(r,'Equip.','Equip','Equipment'),opening,status:pick(r,'Arr. Status','Arr Status','Dep. Status','Arr/Dep Status'),...docs()})}
async function importReport(e){e.preventDefault();try{const date=$('reportDate').value,rows=await readSheet(pendingFile),flights=rows.map((r,i)=>normalizeFlight(r,i,date)).filter(Boolean);if(!flights.length)throw Error('No rows with a flight number and Door Opening (Mins.) were found.');state.days[date]={date,fileName:pendingFile.name,uploadedAt:new Date().toISOString(),flights};selectedDate=date;calendarDate=new Date(`${date}T12:00:00`);saveState();hide('uploadModal');renderAll();toast(`${flights.length} flights imported.`)}catch(e){toast(`Import failed: ${e.message}`)}}
const allFlights=()=>Object.values(state.days).flatMap(d=>d.flights||[]);
function renderAll(){renderDashboard();renderCalendar();renderFlights();renderEmployees()}
function renderDashboard(){const f=allFlights(),m=f.filter(x=>x.metricMet!==null),met=m.filter(x=>x.metricMet).length,late=f.filter(x=>x.lateOpening).length,dates=Object.keys(state.days).sort().reverse();$('dashboard').innerHTML=`<div class="grid metrics"><div class="metric"><span>Retained flight days</span><strong>${dates.length}</strong></div><div class="metric"><span>Flights</span><strong>${f.length}</strong></div><div class="metric"><span>Opening compliance</span><strong>${m.length?Math.round(met/m.length*100):0}%</strong></div><div class="metric"><span>Late door openings</span><strong>${late}</strong></div></div><div class="card"><div class="card-head"><div><h2>Recent reports</h2><p>Open any date in its flight workspace.</p></div></div>${dates.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>File</th><th>Flights</th><th>Late openings</th><th></th></tr></thead><tbody>${dates.map(d=>`<tr><td><b>${pretty(d)}</b></td><td>${esc(state.days[d].fileName)}</td><td>${state.days[d].flights.length}</td><td><span class="pill ${state.days[d].flights.some(x=>x.lateOpening)?'no':'yes'}">${state.days[d].flights.filter(x=>x.lateOpening).length}</span></td><td><button class="btn light" onclick="openFlights('${d}')">View flights</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Upload a CSV or Excel report to begin.</div>'}</div>`}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),start=new Date(y,m,1-new Date(y,m,1).getDay()),today=iso(new Date()),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),day=state.days[key],late=day?.flights.filter(x=>x.lateOpening).length||0;cells.push(`<div class="day ${d.getMonth()!==m?'muted':''} ${key===today?'today':''} ${key===selectedDate?'selected':''}" onclick="selectDay('${key}')"><span class="day-num">${d.getDate()}</span>${day?`<div class="day-event">${day.flights.length} flights</div>`:''}${late?`<div class="day-event late">${late} late</div>`:''}</div>`)}const day=state.days[selectedDate];$('calendar').innerHTML=`<div class="calendar-layout"><div class="card calendar-card"><div class="calendar-head"><div class="calendar-title">${calendarDate.toLocaleDateString(undefined,{month:'long'})} · ${y}</div><div class="calendar-controls"><button onclick="moveMonth(-1)">‹</button><button onclick="goToday()">Today</button><button onclick="moveMonth(1)">›</button></div></div><div class="weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div><aside class="card day-panel"><h3>${pretty(selectedDate)}</h3><div class="date-label">Selected day</div>${day?`<div class="summary-item"><b>${day.flights.length} flights</b><span>${esc(day.fileName)}</span></div><div class="summary-item"><b>${day.flights.filter(x=>x.lateOpening).length} late door openings</b><span>NB over 02:30; 777/787 WB over 03:30</span></div><button class="btn secondary" style="margin-top:15px" onclick="openFlights('${selectedDate}')">View flights</button>`:'<div class="empty">No uploaded report for this date.</div>'}</aside></div>`}
function selectDay(d){selectedDate=d;renderCalendar()}function moveMonth(n){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+n,1);renderCalendar()}function goToday(){calendarDate=new Date();selectedDate=iso(new Date());renderCalendar()}function openFlights(d){selectedDate=d;flightTab='all';switchView('flightWorkspace')}
function renderFlights(){const day=state.days[selectedDate];if(!day){$('flightWorkspace').innerHTML='<div class="empty">Choose a date with an uploaded report from the Calendar.</div>';return}const all=day.flights,late=all.filter(x=>x.lateOpening),list=flightTab==='late'?late:all;$('flightWorkspace').innerHTML=`<div class="workspace-head"><div><span class="eyebrow">${pretty(selectedDate)}</span><h2>Flight workspace</h2><p>${esc(day.fileName)} · ${all.length} flights</p></div><button class="btn primary" onclick="newFlight('${selectedDate}')">Add flight</button></div><div class="subtabs"><button class="subtab ${flightTab==='all'?'active':''}" onclick="setFlightTab('all')">All Flights <span>${all.length}</span></button><button class="subtab ${flightTab==='late'?'active':''}" onclick="setFlightTab('late')">Late Door Openings <span>${late.length}</span></button></div><div class="card">${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Flight</th><th>Gate</th><th>Equip.</th><th>Type</th><th>Door opening</th><th>Target</th><th>Result</th><th>Agent</th><th></th></tr></thead><tbody>${list.map(f=>`<tr><td><b>${esc(f.flightNumber)}</b></td><td>${esc(f.gate||'—')}</td><td>${esc(f.equip||'—')}</td><td>${esc(f.aircraftType)}</td><td>${esc(f.opening)}</td><td>${esc(f.target)}</td><td><span class="pill ${f.lateOpening?'no':f.metricMet===true?'yes':'info'}">${f.lateOpening?'LATE':f.metricMet===true?'MET':'N/A'}</span></td><td>${esc(f.agentName||'Unassigned')}</td><td><button class="btn light" onclick="editFlight('${f.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No flights in this tab.</div>'}</div>`}
function setFlightTab(t){flightTab=t;renderFlights()}function findFlight(id){for(const d of Object.values(state.days)){const f=d.flights.find(x=>x.id===id);if(f)return f}return null}
function newFlight(d){fillFlight(calculate({id:'',date:d,flightNumber:'',gate:'',equip:'',opening:'',status:'',...docs()}));$('recordTitle').textContent='Add flight';show('recordModal')}function editFlight(id){const f=findFlight(id);if(f){fillFlight(f);$('recordTitle').textContent=`Flight ${f.flightNumber}`;show('recordModal')}}
function fillFlight(f){$('recordId').value=f.id||'';$('recordDate').value=f.date||selectedDate;$('agentSearch').value=f.agentName||'';$('agentId').value=f.agentId||'';$('recordCsm').value=f.csm||'';$('recordShift').value=f.shift||'';$('recordFlight').value=f.flightNumber||'';$('recordGate').value=f.gate||'';$('recordEquip').value=f.equip||'';$('recordStatus').value=f.status||'';$('recordDuration').value=f.opening||'';$('recordReason').value=f.reason||'';$('recordAction').value=f.action||'';$('recordFollowUp').value=f.followUp||'';$('recordPositioning').value=f.positioning||'';preview()}
function preview(){const f=calculate({equip:$('recordEquip').value,opening:$('recordDuration').value});$('recordResult').value=f.lateOpening?`LATE — ${f.aircraftType} target ${f.target}`:f.metricMet===true?`MET — ${f.aircraftType} target ${f.target}`:'N/A — unknown aircraft or time'}
function saveFlight(e){e.preventDefault();const oldId=$('recordId').value,old=findFlight(oldId)||{},date=$('recordDate').value,f=calculate({...old,id:oldId||uid(),date,flightNumber:$('recordFlight').value.trim(),gate:$('recordGate').value.trim(),equip:$('recordEquip').value.trim(),status:$('recordStatus').value.trim(),opening:$('recordDuration').value.trim(),agentId:$('agentId').value,agentName:$('agentSearch').value.trim(),csm:$('recordCsm').value.trim(),shift:$('recordShift').value,reason:$('recordReason').value.trim(),action:$('recordAction').value.trim(),followUp:$('recordFollowUp').value.trim(),positioning:$('recordPositioning').value.trim()});if(!state.days[date])state.days[date]={date,fileName:'Manual records',uploadedAt:new Date().toISOString(),flights:[]};Object.values(state.days).forEach(d=>d.flights=d.flights.filter(x=>x.id!==f.id));state.days[date].flights.push(f);selectedDate=date;saveState();hide('recordModal');renderAll();switchView('flightWorkspace');toast('Flight saved and recalculated.')}
function searchAgents(){const q=norm($('agentSearch').value),box=$('agentResults');$('agentId').value='';$('recordCsm').value='';if(q.length<2){box.classList.remove('show');return}const list=employees.filter(e=>[empName(e),e.id,e.email,e.csm].some(v=>norm(v).includes(q))).slice(0,10);box.innerHTML=list.map(e=>`<div class="agent-option" onclick="chooseAgent('${esc(e.id)}')"><b>${esc(empName(e))}</b><small>${esc(e.id)} · ${esc(e.email||'No email')} · CSM ${esc(e.csm||'—')}</small></div>`).join('')||'<div class="agent-option">No employees found</div>';box.classList.add('show')}
function chooseAgent(id){const e=employees.find(x=>String(x.id)===String(id));if(e){$('agentSearch').value=empName(e);$('agentId').value=e.id;$('recordCsm').value=e.csm||'';$('agentResults').classList.remove('show')}}
function renderEmployees(){const teams=[...new Set(employees.map(e=>e.csm).filter(Boolean))].sort();$('employees').innerHTML=`<div class="card"><div class="card-head"><div><h2>Universal Employee Searcher</h2><p>${employees.length} editable profiles available for flight assignments.</p></div><button class="btn primary" onclick="newEmployee()">Add employee</button></div><div class="filters"><div class="search"><input id="directorySearch" placeholder="Search name, email, employee ID, or CSM"></div><select id="directoryCsm"><option value="">All CSMs</option>${teams.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="directoryResults"></div></div>`;$('directorySearch').oninput=renderEmployeeResults;$('directoryCsm').onchange=renderEmployeeResults;renderEmployeeResults()}
function renderEmployeeResults(){const q=norm($('directorySearch')?.value),team=$('directoryCsm')?.value||'',list=employees.filter(e=>(!team||e.csm===team)&&(!q||[empName(e),e.id,e.email,e.csm].some(v=>norm(v).includes(q)))).slice(0,100);$('directoryResults').innerHTML=list.length?list.map(e=>`<div class="employee-row"><div><span class="eyebrow">EMPLOYEE</span><div class="employee-name">${esc(empName(e))}</div><div class="hint">${esc(e.email||'No email')}</div></div><div><span class="eyebrow">EMPLOYEE ID</span>${esc(e.id||'—')}</div><div><span class="eyebrow">CSM</span>${esc(e.csm||'—')}</div><div><button class="btn light" onclick="editEmployee('${esc(e.id)}')">Edit</button></div></div>`).join(''):'<div class="empty">No employees found.</div>'}
function newEmployee(){fillEmployee({});$('employeeTitle').textContent='Add employee';$('deleteEmployeeBtn').style.display='none';show('employeeModal')}function editEmployee(id){const e=employees.find(x=>String(x.id)===String(id));if(e){fillEmployee(e);$('employeeTitle').textContent=empName(e);$('deleteEmployeeBtn').style.display='inline-block';show('employeeModal')}}
function fillEmployee(e){$('employeeOriginalId').value=e.id||'';$('employeeFirst').value=e.firstName||'';$('employeeLast').value=e.lastName||'';$('employeeId').value=e.id||'';$('employeeEmail').value=e.email||'';$('employeeCsm').value=e.csm||'';$('employeeCsc').value=e.cscQualified||'';$('employeeAnte').value=e.antePost||'';$('employeeAnniversary').value=e.anniversary||'';$('employeeNotes').value=e.notes||''}
function saveEmployee(ev){ev.preventDefault();const old=$('employeeOriginalId').value,id=$('employeeId').value.trim();if(id!==old&&employees.some(e=>String(e.id)===id)){toast('That employee ID already exists.');return}const e={firstName:$('employeeFirst').value.trim(),lastName:$('employeeLast').value.trim(),id,email:$('employeeEmail').value.trim(),csm:$('employeeCsm').value.trim(),cscQualified:$('employeeCsc').value,antePost:$('employeeAnte').value,anniversary:$('employeeAnniversary').value,notes:$('employeeNotes').value.trim()};e.name=`${e.lastName}, ${e.firstName}`;const i=employees.findIndex(x=>String(x.id)===String(old));if(i>=0)employees[i]=e;else employees.push(e);allFlights().forEach(f=>{if(String(f.agentId)===String(old)){f.agentId=e.id;f.agentName=empName(e);f.csm=e.csm}});saveEmployees();saveState();hide('employeeModal');renderAll();switchView('employees');toast('Employee saved.')}
function deleteEmployee(){const id=$('employeeOriginalId').value,e=employees.find(x=>String(x.id)===String(id));if(!e||!confirm(`Delete ${empName(e)} from this browser's roster?`))return;employees=employees.filter(x=>String(x.id)!==String(id));saveEmployees();hide('employeeModal');renderAll();switchView('employees');toast('Employee deleted.')}
function exportData(){const b=new Blob([JSON.stringify({version:3,exportedAt:new Date().toISOString(),retentionDays:7,...state,employees},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`door-operations-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)}
Object.assign(window,{selectDay,moveMonth,goToday,openFlights,setFlightTab,newFlight,editFlight,chooseAgent,newEmployee,editEmployee});boot();
