const STATE_KEY='ord_door_ops_v2', EMPLOYEE_KEY='ord_customer_care_fall_2026_v3', DAY=86400000;
let state={days:{},records:[]},employees=[],pendingFile=null,calendarDate=new Date(),selectedDate=isoDate(new Date());
const $=id=>document.getElementById(id), norm=v=>String(v??'').trim().toLowerCase();
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function isoDate(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function prettyDate(s){return new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function displayName(e){return `${e.lastName||''}${e.firstName?`, ${e.firstName}`:''}`.replace(/^, /,'')||e.name||'Unnamed employee'}

async function boot(){
  try{employees=JSON.parse(localStorage.getItem(EMPLOYEE_KEY)||'null')||await fetch('data/employees.json').then(r=>r.json())}catch{employees=[]}
  try{state={days:{},records:[],...JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}}catch{state={days:{},records:[]}}
  cleanup(); bind(); renderAll();
}
function cleanup(){const cutoff=Date.now()-7*DAY;Object.keys(state.days).forEach(date=>{if(new Date(`${date}T23:59:59`).getTime()<cutoff)delete state.days[date]});state.records=state.records.filter(r=>new Date(`${r.date}T23:59:59`).getTime()>=cutoff);save()}
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function bind(){
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
  document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)hideModal(close.dataset.close)});
  $('reportFile').onchange=e=>{pendingFile=e.target.files[0];if(!pendingFile)return;$('reportDate').value=isoDate(new Date());showModal('uploadModal')};
  $('uploadForm').onsubmit=importReport;$('recordForm').onsubmit=saveRecord;$('agentSearch').oninput=searchAgents;$('exportBtn').onclick=exportData;
  window.onclick=e=>{if(e.target.classList.contains('modal'))hideModal(e.target.id)};
}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));if(view==='calendar')renderCalendar();if(view==='closings')renderClosings();if(view==='employees')renderEmployees()}
function showModal(id){$(id).classList.add('show');$(id).setAttribute('aria-hidden','false')}
function hideModal(id){$(id).classList.remove('show');$(id).setAttribute('aria-hidden','true');if(id==='uploadModal'){$('reportFile').value='';pendingFile=null}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}

async function importReport(e){
  e.preventDefault();if(!pendingFile)return;const date=$('reportDate').value;
  try{const rows=await readSheet(pendingFile),flights=rows.map((r,i)=>normalizeFlight(r,i,date)).filter(Boolean);if(!flights.length)throw new Error('No usable flight rows were found. Check the report headers.');state.days[date]={date,fileName:pendingFile.name,uploadedAt:new Date().toISOString(),flights};state.records=state.records.filter(r=>!(r.auto&&r.date===date));flights.filter(f=>f.lateClosing).forEach(f=>state.records.push(recordFromFlight(f,date)));save();selectedDate=date;calendarDate=new Date(`${date}T12:00:00`);hideModal('uploadModal');renderAll();toast(`${flights.length} flights saved under ${prettyDate(date)}.`)}catch(err){toast(`Import failed: ${err.message}`)}
}
function readSheet(file){return new Promise((resolve,reject)=>{const ext=file.name.split('.').pop().toLowerCase();if(ext==='csv'){Papa.parse(file,{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim(),complete:r=>resolve(r.data),error:reject})}else{const reader=new FileReader();reader.onload=()=>{try{const wb=XLSX.read(reader.result,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];resolve(XLSX.utils.sheet_to_json(ws,{defval:'',raw:false}))}catch(err){reject(err)}};reader.onerror=()=>reject(reader.error);reader.readAsArrayBuffer(file)}})}
function pick(row,...names){const keys=Object.keys(row);for(const n of names){const k=keys.find(x=>norm(x)===norm(n));if(k&&String(row[k]??'').trim()!=='')return String(row[k]).trim()}return''}
function seconds(v){const s=String(v??'').trim();if(!s)return null;if(/^[-+]?\d+:\d{1,2}$/.test(s)){const sign=s.startsWith('-')?-1:1,[m,sec]=s.replace(/^[-+]/,'').split(':').map(Number);return sign*(m*60+sec)}const n=Number(s);return Number.isFinite(n)?Math.round(n*60):null}
function aircraft(equip){const c=String(equip).toUpperCase().replace(/[^A-Z0-9]/g,'');if(/777|787|789/.test(c))return{type:'WB',target:210,targetText:'03:30'};if(/319|320|321|738/.test(c))return{type:'NB',target:150,targetText:'02:30'};return{type:'Unknown',target:null,targetText:'N/A'}}
function normalizeFlight(row,i,date){
  const flight=pick(row,'Arr. Flt.','Arr Flt.','Arrival Flight','Dep. Flt.','Dep Flt.','Flight Number');if(!flight)return null;
  const opening=pick(row,'Door Opening (Mins.)','Door Opening','Door Open (Mins.)'),closing=pick(row,'Door Closing (Mins.)','Door Closing','Late Door Closing (Mins.)','Door Close (Mins.)');if(!opening&&!closing)return null;
  const equip=pick(row,'Equip.','Equip','Equipment'),a=aircraft(equip),openSec=seconds(opening),closeSec=seconds(closing);
  const explicitLate=/late|miss|no/i.test(pick(row,'Door Closing Status','Closing Status','Metric Met'));
  return{id:`${date}-${flight}-${i}`,date,flightNumber:flight,gate:pick(row,'ETA/Actual Gate','Sch Arr. Gate','Sch Arr Gate','ETD/Actual Gate','Sch Dep. Gate','Sch Dep Gate'),equip,aircraftType:a.type,opening,openingSeconds:openSec,target:a.targetText,metricMet:a.target===null||openSec===null?null:openSec<=a.target,closing,closingSeconds:closeSec,lateClosing:Boolean(closing)&&(explicitLate||closeSec>0),status:pick(row,'Arr. Status','Arr Status','Dep. Status','Arr/Dep Status')}
}
function recordFromFlight(f,date){return{id:uid(),auto:true,flightId:f.id,date,flight:f.flightNumber,gate:f.gate,duration:f.closing,agentId:'',agentName:'',csm:'',shift:'',reason:'',action:'',followUp:'',positioning:''}}

function allFlights(){return Object.values(state.days).flatMap(d=>d.flights)}
function renderAll(){renderDashboard();renderCalendar();renderClosings();renderEmployees()}
function renderDashboard(){const flights=allFlights(),measured=flights.filter(f=>f.metricMet!==null),met=measured.filter(f=>f.metricMet).length,late=state.records.length,dates=Object.keys(state.days).sort().reverse();$('dashboard').innerHTML=`<div class="grid metrics"><div class="metric"><span>Retained flight days</span><strong>${dates.length}</strong></div><div class="metric"><span>Flights</span><strong>${flights.length}</strong></div><div class="metric"><span>Opening compliance</span><strong>${measured.length?Math.round(met/measured.length*100):0}%</strong></div><div class="metric"><span>Late closings</span><strong>${late}</strong></div></div><div class="card"><div class="card-head"><div><h2>Recent reports</h2><p>Reports remain in this browser for seven days.</p></div><label class="btn primary file-btn">Upload report<input type="file" accept=".csv,.xlsx,.xls" hidden onchange="document.getElementById('reportFile').files=this.files;document.getElementById('reportFile').dispatchEvent(new Event('change'))"></label></div>${dates.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>File</th><th>Flights</th><th>Opening misses</th><th>Late closings</th><th></th></tr></thead><tbody>${dates.map(date=>{const d=state.days[date],miss=d.flights.filter(f=>f.metricMet===false).length,lc=state.records.filter(r=>r.date===date).length;return`<tr><td><b>${prettyDate(date)}</b></td><td>${esc(d.fileName)}</td><td>${d.flights.length}</td><td><span class="pill ${miss?'no':'yes'}">${miss}</span></td><td><span class="pill ${lc?'no':'yes'}">${lc}</span></td><td><button class="btn light" onclick="openDay('${date}')">View</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Upload a CSV or Excel report to begin.</div>'}</div>${renderFlightTable(dates[0])}`}
function renderFlightTable(date){if(!date||!state.days[date])return'';const fs=state.days[date].flights;return`<div class="card"><div class="card-head"><div><h2>${prettyDate(date)} flights</h2><p>${esc(state.days[date].fileName)}</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Flight</th><th>Gate</th><th>Equip.</th><th>Type</th><th>Door opening</th><th>Target</th><th>Met</th><th>Door closing</th></tr></thead><tbody>${fs.map(f=>`<tr><td><b>${esc(f.flightNumber)}</b></td><td>${esc(f.gate||'—')}</td><td>${esc(f.equip||'—')}</td><td>${esc(f.aircraftType)}</td><td>${esc(f.opening||'—')}</td><td>${esc(f.target)}</td><td><span class="pill ${f.metricMet===true?'yes':f.metricMet===false?'no':'info'}">${f.metricMet===true?'YES':f.metricMet===false?'NO':'N/A'}</span></td><td>${esc(f.closing||'—')}</td></tr>`).join('')}</tbody></table></div></div>`}
function openDay(date){selectedDate=date;calendarDate=new Date(`${date}T12:00:00`);switchView('calendar')}

function renderCalendar(){
  const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=isoDate(new Date()),cells=[];
  for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=isoDate(d),day=state.days[iso],late=state.records.filter(r=>r.date===iso).length;cells.push(`<div class="day ${d.getMonth()!==m?'muted':''} ${iso===today?'today':''} ${iso===selectedDate?'selected':''}" onclick="selectDay('${iso}')"><span class="day-num">${d.getDate()}</span>${day?`<div class="day-event">${day.flights.length} flights</div>`:''}${late?`<div class="day-event late">${late} late</div>`:''}</div>`)}
  const day=state.days[selectedDate],records=state.records.filter(r=>r.date===selectedDate);$('calendar').innerHTML=`<div class="calendar-layout"><div class="card calendar-card"><div class="calendar-head"><div class="calendar-title">${calendarDate.toLocaleDateString(undefined,{month:'long'})} · ${y}</div><div class="calendar-controls"><button onclick="moveMonth(-1)">‹</button><button onclick="goToday()">Today</button><button onclick="moveMonth(1)">›</button></div></div><div class="weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div><aside class="card day-panel"><h3>${prettyDate(selectedDate)}</h3><div class="date-label">Selected day</div>${day?`<div class="summary-item"><b>${day.flights.length} flights</b><span>${esc(day.fileName)}</span></div><div class="summary-item"><b>${day.flights.filter(f=>f.metricMet===false).length} opening misses</b><span>Outside the aircraft threshold</span></div><div class="summary-item"><b>${records.length} late closings</b><span>Documented records</span></div><button class="btn secondary" style="margin-top:15px" onclick="viewSelectedFlights()">View flights</button>`:'<div class="empty">No uploaded report for this date.</div>'}<button class="btn primary" style="margin-top:10px" onclick="newRecord('${selectedDate}')">Add late closing</button></aside></div>`}
function selectDay(date){selectedDate=date;renderCalendar()}function moveMonth(n){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+n,1);renderCalendar()}function goToday(){calendarDate=new Date();selectedDate=isoDate(new Date());renderCalendar()}function viewSelectedFlights(){const html=renderFlightTable(selectedDate);$('dashboard').innerHTML=html;switchView('dashboard')}

function renderClosings(){const rows=[...state.records].sort((a,b)=>b.date.localeCompare(a.date));$('closings').innerHTML=`<div class="card"><div class="card-head"><div><h2>Late Door Closings</h2><p>Assign an agent and document each event.</p></div><button class="btn primary" onclick="newRecord('${isoDate(new Date())}')">Add record</button></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Flight</th><th>Gate</th><th>Duration</th><th>Agent</th><th>CSM</th><th>Shift</th><th>Reason</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${prettyDate(r.date)}</td><td>${esc(r.flight||'—')}</td><td>${esc(r.gate||'—')}</td><td><span class="pill no">${esc(r.duration||'—')}</span></td><td>${esc(r.agentName||'Unassigned')}</td><td>${esc(r.csm||'—')}</td><td>${esc(r.shift||'—')}</td><td title="${esc(r.reason)}">${esc(r.reason||'Needs documentation')}</td><td><button class="btn light" onclick="editRecord('${r.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No late door closings are stored.</div>'}</div>`}
function newRecord(date){fillRecord({id:'',date,flight:'',gate:'',duration:'',agentId:'',agentName:'',csm:'',shift:'',reason:'',action:'',followUp:'',positioning:''});$('recordTitle').textContent='Add late door closing';showModal('recordModal')}
function editRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;fillRecord(r);$('recordTitle').textContent=`Flight ${r.flight||'record'}`;showModal('recordModal')}
function fillRecord(r){$('recordId').value=r.id||'';$('recordDate').value=r.date||isoDate(new Date());$('agentSearch').value=r.agentName||'';$('agentId').value=r.agentId||'';$('recordCsm').value=r.csm||'';$('recordShift').value=r.shift||'';$('recordFlight').value=r.flight||'';$('recordGate').value=r.gate||'';$('recordDuration').value=r.duration||'';$('recordReason').value=r.reason||'';$('recordAction').value=r.action||'';$('recordFollowUp').value=r.followUp||'';$('recordPositioning').value=r.positioning||'';$('agentResults').classList.remove('show')}
function saveRecord(e){e.preventDefault();const id=$('recordId').value,old=state.records.find(r=>r.id===id)||{};const r={...old,id:id||uid(),auto:old.auto||false,date:$('recordDate').value,agentId:$('agentId').value,agentName:$('agentSearch').value.trim(),csm:$('recordCsm').value.trim(),shift:$('recordShift').value,flight:$('recordFlight').value.trim(),gate:$('recordGate').value.trim(),duration:$('recordDuration').value.trim(),reason:$('recordReason').value.trim(),action:$('recordAction').value.trim(),followUp:$('recordFollowUp').value.trim(),positioning:$('recordPositioning').value.trim()};const idx=state.records.findIndex(x=>x.id===r.id);if(idx>=0)state.records[idx]=r;else state.records.push(r);save();hideModal('recordModal');renderAll();switchView('closings');toast('Late closing record saved.')}
function searchAgents(){const q=norm($('agentSearch').value),box=$('agentResults');$('agentId').value='';$('recordCsm').value='';if(q.length<2){box.classList.remove('show');return}const found=employees.filter(e=>[displayName(e),e.id,e.email,e.csm].some(v=>norm(v).includes(q))).slice(0,10);box.innerHTML=found.map(e=>`<div class="agent-option" onclick="chooseAgent('${esc(e.id)}')"><b>${esc(displayName(e))}</b><small>${esc(e.id)} · ${esc(e.email||'No email')} · CSM ${esc(e.csm||'—')}</small></div>`).join('')||'<div class="agent-option">No employees found</div>';box.classList.add('show')}
function chooseAgent(id){const e=employees.find(x=>String(x.id)===String(id));if(!e)return;$('agentSearch').value=displayName(e);$('agentId').value=e.id;$('recordCsm').value=e.csm||'';$('agentResults').classList.remove('show')}

function renderEmployees(){const csm=[...new Set(employees.map(e=>e.csm).filter(Boolean))].sort();$('employees').innerHTML=`<div class="card"><div class="card-head"><div><h2>Universal Employee Searcher</h2><p>${employees.length} employee profiles available for flight assignments.</p></div></div><div class="filters"><div class="search"><input id="directorySearch" placeholder="Search name, email, employee ID, or CSM"></div><select id="directoryCsm"><option value="">All CSMs</option>${csm.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="directoryResults"></div></div>`;$('directorySearch').oninput=renderEmployeeResults;$('directoryCsm').onchange=renderEmployeeResults;renderEmployeeResults()}
function renderEmployeeResults(){const q=norm($('directorySearch')?.value),csm=$('directoryCsm')?.value||'',list=employees.filter(e=>(!csm||e.csm===csm)&&(!q||[displayName(e),e.id,e.email,e.csm].some(v=>norm(v).includes(q)))).slice(0,100);$('directoryResults').innerHTML=list.length?list.map(e=>`<div class="employee-row"><div><span class="eyebrow">EMPLOYEE</span><div class="employee-name">${esc(displayName(e))}</div><div class="hint">${esc(e.email||'No email')}</div></div><div><span class="eyebrow">EMPLOYEE ID</span>${esc(e.id||'—')}</div><div><span class="eyebrow">CSM</span>${esc(e.csm||'—')}</div></div>`).join(''):'<div class="empty">No employees found.</div>'}
function exportData(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),retentionDays:7,...state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`door-operations-${isoDate(new Date())}.json`;a.click();URL.revokeObjectURL(a.href);toast('JSON downloaded.')}

window.openDay=openDay;window.selectDay=selectDay;window.moveMonth=moveMonth;window.goToday=goToday;window.viewSelectedFlights=viewSelectedFlights;window.newRecord=newRecord;window.editRecord=editRecord;window.chooseAgent=chooseAgent;
boot();
